title: Haokun's Blog
description: 分享技术、生活与思考
author: Haokun
email: your-email@example.com

baseurl: ""
url: "https://Marinkun.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: /:year/:month/:day/:title/

header_pages:
  - index.md
  - about.md

minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/Marinkun" }

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
